<%-- 
    Document   : output
    Created on : Sep 17, 2017, 10:22:07 PM
    Author     : Thomas Hartmann - tha@cphbusiness.dk
--%>

<%@page contentType="text/html" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>JSP Page</title>
    </head>
    <body>
        <h2>Explanation</h2>
        <p>This came from the user in the form that was send to the server with a POST request. The server send a response back to the browser generated by this jsp page. The JSP page that is loaded with the request dispatcher's forward method has access to the request object and there by to the attributes that was set on it.</p>
        <p>The information that was send from the form was:</p> Input = <%= request.getAttribute("userInput") %> and Hidden = <% out.print(request.getParameter("origin"));%>
        <br><a href="cars.jsp">Click here</a> to go to a new pages and see how data attached to the session object is available on any JSP page as long as the session is running
        
    </body>
</html>
